// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntubmznmcnzadbnpvdif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50dWJtem5tY256YWRibnB2ZGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzgxODYsImV4cCI6MjA2MjIxNDE4Nn0.zu72mq6jLit7bPEeRtO8-4ullt4wMiF_w-nZAXDkTEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);